// default package
// Generated Apr 17, 2015 6:38:31 PM by Hibernate Tools 3.4.0.CR1

import java.util.Date;

/**
 * DataRegisterData generated by hbm2java
 */
public class DataRegisterData implements java.io.Serializable {

	private Integer dataRegisterRecordId;
	private Date timestamp;
	private int smId;
	private byte[] dataRegisterRecordValue;
	private Date cloudTimestamp;

	public DataRegisterData() {
	}

	public DataRegisterData(int smId) {
		this.smId = smId;
	}

	public DataRegisterData(int smId, byte[] dataRegisterRecordValue,
			Date cloudTimestamp) {
		this.smId = smId;
		this.dataRegisterRecordValue = dataRegisterRecordValue;
		this.cloudTimestamp = cloudTimestamp;
	}

	public Integer getDataRegisterRecordId() {
		return this.dataRegisterRecordId;
	}

	public void setDataRegisterRecordId(Integer dataRegisterRecordId) {
		this.dataRegisterRecordId = dataRegisterRecordId;
	}

	public Date getTimestamp() {
		return this.timestamp;
	}

	public void setTimestamp(Date timestamp) {
		this.timestamp = timestamp;
	}

	public int getSmId() {
		return this.smId;
	}

	public void setSmId(int smId) {
		this.smId = smId;
	}

	public byte[] getDataRegisterRecordValue() {
		return this.dataRegisterRecordValue;
	}

	public void setDataRegisterRecordValue(byte[] dataRegisterRecordValue) {
		this.dataRegisterRecordValue = dataRegisterRecordValue;
	}

	public Date getCloudTimestamp() {
		return this.cloudTimestamp;
	}

	public void setCloudTimestamp(Date cloudTimestamp) {
		this.cloudTimestamp = cloudTimestamp;
	}

}
