// default package
// Generated Apr 17, 2015 6:38:31 PM by Hibernate Tools 3.4.0.CR1

import java.util.Date;

/**
 * SmartMeterLightData generated by hbm2java
 */
public class SmartMeterLightData implements java.io.Serializable {

	private int id;
	private Date timestamp;
	private int smId;
	private int lightId;
	private Integer tempValue;
	private Integer maxTempValue;
	private Integer minTempValue;
	private Integer status;
	private Date cloudTimestamp;

	public SmartMeterLightData() {
	}

	public SmartMeterLightData(int id, int smId, int lightId) {
		this.id = id;
		this.smId = smId;
		this.lightId = lightId;
	}

	public SmartMeterLightData(int id, int smId, int lightId,
			Integer tempValue, Integer maxTempValue, Integer minTempValue,
			Integer status, Date cloudTimestamp) {
		this.id = id;
		this.smId = smId;
		this.lightId = lightId;
		this.tempValue = tempValue;
		this.maxTempValue = maxTempValue;
		this.minTempValue = minTempValue;
		this.status = status;
		this.cloudTimestamp = cloudTimestamp;
	}

	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	public Date getTimestamp() {
		return this.timestamp;
	}

	public void setTimestamp(Date timestamp) {
		this.timestamp = timestamp;
	}

	public int getSmId() {
		return this.smId;
	}

	public void setSmId(int smId) {
		this.smId = smId;
	}

	public int getLightId() {
		return this.lightId;
	}

	public void setLightId(int lightId) {
		this.lightId = lightId;
	}

	public Integer getTempValue() {
		return this.tempValue;
	}

	public void setTempValue(Integer tempValue) {
		this.tempValue = tempValue;
	}

	public Integer getMaxTempValue() {
		return this.maxTempValue;
	}

	public void setMaxTempValue(Integer maxTempValue) {
		this.maxTempValue = maxTempValue;
	}

	public Integer getMinTempValue() {
		return this.minTempValue;
	}

	public void setMinTempValue(Integer minTempValue) {
		this.minTempValue = minTempValue;
	}

	public Integer getStatus() {
		return this.status;
	}

	public void setStatus(Integer status) {
		this.status = status;
	}

	public Date getCloudTimestamp() {
		return this.cloudTimestamp;
	}

	public void setCloudTimestamp(Date cloudTimestamp) {
		this.cloudTimestamp = cloudTimestamp;
	}

}
