// default package
// Generated Apr 17, 2015 6:38:31 PM by Hibernate Tools 3.4.0.CR1

import java.util.Date;

/**
 * SmartMeterLoadDataRefined generated by hbm2java
 */
public class SmartMeterLoadDataRefined implements java.io.Serializable {

	private Integer id;
	private Date timestamp;
	private int smId;
	private int smLoadId;
	private String smLoadName;
	private Integer voltageValue;
	private Float currentValue;
	private byte[] thetaValue;
	private Float power;
	private Float energy;
	private Integer status;
	private Date cloudTimestamp;

	public SmartMeterLoadDataRefined() {
	}

	public SmartMeterLoadDataRefined(int smId, int smLoadId) {
		this.smId = smId;
		this.smLoadId = smLoadId;
	}

	public SmartMeterLoadDataRefined(int smId, int smLoadId, String smLoadName,
			Integer voltageValue, Float currentValue, byte[] thetaValue,
			Float power, Float energy, Integer status, Date cloudTimestamp) {
		this.smId = smId;
		this.smLoadId = smLoadId;
		this.smLoadName = smLoadName;
		this.voltageValue = voltageValue;
		this.currentValue = currentValue;
		this.thetaValue = thetaValue;
		this.power = power;
		this.energy = energy;
		this.status = status;
		this.cloudTimestamp = cloudTimestamp;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public Date getTimestamp() {
		return this.timestamp;
	}

	public void setTimestamp(Date timestamp) {
		this.timestamp = timestamp;
	}

	public int getSmId() {
		return this.smId;
	}

	public void setSmId(int smId) {
		this.smId = smId;
	}

	public int getSmLoadId() {
		return this.smLoadId;
	}

	public void setSmLoadId(int smLoadId) {
		this.smLoadId = smLoadId;
	}

	public String getSmLoadName() {
		return this.smLoadName;
	}

	public void setSmLoadName(String smLoadName) {
		this.smLoadName = smLoadName;
	}

	public Integer getVoltageValue() {
		return this.voltageValue;
	}

	public void setVoltageValue(Integer voltageValue) {
		this.voltageValue = voltageValue;
	}

	public Float getCurrentValue() {
		return this.currentValue;
	}

	public void setCurrentValue(Float currentValue) {
		this.currentValue = currentValue;
	}

	public byte[] getThetaValue() {
		return this.thetaValue;
	}

	public void setThetaValue(byte[] thetaValue) {
		this.thetaValue = thetaValue;
	}

	public Float getPower() {
		return this.power;
	}

	public void setPower(Float power) {
		this.power = power;
	}

	public Float getEnergy() {
		return this.energy;
	}

	public void setEnergy(Float energy) {
		this.energy = energy;
	}

	public Integer getStatus() {
		return this.status;
	}

	public void setStatus(Integer status) {
		this.status = status;
	}

	public Date getCloudTimestamp() {
		return this.cloudTimestamp;
	}

	public void setCloudTimestamp(Date cloudTimestamp) {
		this.cloudTimestamp = cloudTimestamp;
	}

}
